Use octokit rest
Parsimotion/github-to-pivotal pull request #7
Opened 2021-04-20 18:49 UTC by kevinszuchet

Github ya deprecó el tema de pasarle el token por qs. Además, el npm de github está deprecadísimo también así que lo paso a `@octokit/rest`

2021-04-20 19:21 UTC, lclauser requested changes
Medio macabro que esten los `node_modules` aca, mas sabiendo que es un package y se van ampliamente ignorados, asi que habria que sacarlos.
Agregar un `.gitignore`?

2021-04-21 14:03 UTC, kevinszuchet commented
@lclauser si lo se, me quedcaron de ayer, en realidad están en el git ignore, pero por alguna raazón no los está ignorando. Tal vezx porque quedaron como los commits viejos cuando si se subían...

2021-04-21 14:03 UTC, kevinszuchet commented
@lclauser si lo se, me quedcaron de ayer, en realidad están en el git ignore, pero por alguna raazón no los está ignorando. Tal vezx porque quedaron como los commits viejos cuando si se subían...

2021-04-21 14:43 UTC, lclauser approved these changes
Al ser un package tampoco usa el package-lock asi que tambien se podria borrar

2021-04-21 14:45 UTC, merged